
###
post http://localhost:3001/api/blogs
content-type:application/json

{
    "author":"Sushil",
    "url":"http://sushil/new",
    "title":"sushil Blog"
}

########
delete http://localhost:3001/api/blogs/2
