
###
post http://localhost:3001/api/blogs
content-type:application/json
authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1c2hpbDBAZ21haWwuY29tIiwiaWQiOjcsImlhdCI6MTc2NTAyMjA4Mn0.4LPjJVNzfBmrIaT7kdSB5eKAaAqyMCLX8cAniKMbA78

{
    "author":"Sushil0",
    "url":"http://sushil/after0Token",
    "title":"sushil Blog after 0 token"
}


###########

DELETE http://localhost:3001/api/blogs/6
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1c2hpbDBAZ21haWwuY29tIiwiaWQiOjcsImlhdCI6MTc2NTAyMjA4Mn0.4LPjJVNzfBmrIaT7kdSB5eKAaAqyMCLX8cAniKMbA78



###
put http://localhost:3001/api/blogs/1
content-type:application/json

{
    "likes": 2
}

########

post http://localhost:3001/api/users
content-type:application/json

{
    "username":"sushil0@gmail.com",
    "name":"Sushil"
}

##
###
PUT http://localhost:3001/api/users/sushil
content-type: application/json

{
    "username": "sudesh"
}

########

post http://localhost:3001/api/login
content-type:application/json

{
    "username":"sushil0@gmail.com",
    "password":"secret"
}