
###
post http://localhost:3001/api/blogs
content-type:application/json

{
    "author":"Sushil",
    "url":"http://sushil/new",
    "title":"sushil Blog"
}

########
delete http://localhost:3001/api/blogs/2

###
put http://localhost:3001/api/blogs/1
content-type:application/json

{
    "likes": 2
}

########

post http://localhost:3001/api/users
content-type:application/json

{
    "username":"sushil",
    "name":"Sushil"
}

##
###
PUT http://localhost:3001/api/users/sushil
content-type: application/json

{
    "username": "sudesh"
}
