##GET all persons
get http://localhost:3001/api/blogs


#######
post http://localhost:3001/api/blogs
content-type: application/json

{
  "title": "file distructure 3",
  "author": "full stack open 3",
  "url": " http://localhost:3001/api/blogs/file-distructure3",
  "likes": "333"
}

