##GET all persons
get http://localhost:3001/api/blogs


#######
post http://localhost:3001/api/blogs
content-type: application/json

{
  "title": "file 443",
  "author": "full 3332",
  "url": " http://localhost:3001/api/blogs/file-distr3uctu3re5",
  "likes": "331323",
  "userID":"68ba94b121cbe490c4d70bca"
}

###########  user create

post http://localhost:3001/api/users
content-type: application/json

{
  "username": "muskan",
  "name": "miskan tamang ",
  "password": "muskan"
}

############  login

post http://localhost:3001/api/login
content-type: application/json

{
  "username": "muskan",
  "name": "miskan tamang ",
  "password": "muskan"
}


